### PR TITLE
Fixes #1 - improved type length analysis

### LINKED ISSUE #1: Extensions ignored in type length analysis
How to reproduce:

1. Create empty directory named "Foobar"
2. Initialize swift package via `$ swift package init`
3. Change …

    ```swift
    struct Foobar {
        var text = "Hello, World!"
    }
    ```

    … to …

```swift
struct Foobar {
    var text = "Hello, World!"
// }

// extension Foobar {
    func foo() -> Int {
        var i: Int = 0
        i += 1
        i += 1
        i += 1
        i += 1
        i += 1
        i += 1
        i += 1
        i += 1
        i += 1
        i += 1
        i += 1
        i += 1
        i += 1
        i += 1
        i += 1
        i += 1
        i += 1
        i += 1
        i += 1
        i += 1
        i += 1
        i += 1
        i += 1
        i += 1
        i += 1
        i += 1
        i += 1
        i += 1
        i += 1
        i += 1
        i += 1
        i += 1
        i += 1
        i += 1
        i += 1
        i += 1
        return i
    }
}
```

4. run `$ sitrep`

```
Overview
   Files scanned: 5
   Structs: 1
   Classes: 1
   Enums: 0
   Protocols: 0
   Extensions: 0

Sizes
   Total lines of code: 105
   Source lines of code: 93
   Longest file: Foobar.swift (45 source lines)
   Longest type: Foobar (45 source lines)

Structure
   Imports: XCTest (3), FoobarTests (1), Foobar (1), PackageDescription (1)
   UIKit View Controllers: 0
   UIKit Views: 0
   SwiftUI Views: 0
```

5. Uncomment these lines …

```swift
// }

// extension Foobar {
```

6. run `$ sitrep` again

```diff
Overview
   Files scanned: 5
   Structs: 1
   Classes: 1
   Enums: 0
   Protocols: 0
---   Extensions: 0
+++   Extensions: 1

Sizes
   Total lines of code: 105
   Source lines of code: 93
   Longest file: Foobar.swift (45 source lines)
---   Longest type: Foobar (45 source lines)
+++   Longest type: FoobarTests (11 source lines)

Structure
   Imports: XCTest (3), FoobarTests (1), Foobar (1), PackageDescription (1)
   UIKit View Controllers: 0
   UIKit Views: 0
   SwiftUI Views: 0
```

7. Notice how `Foobar` is now suddenly not considered the longest type any more.

This is wrong.  
The contents of a type's extensions should be considered content of the type.

### PR DESCRIPTION
**Pull request by alexito4**
This fixes #1 by gathering all types (no matter which kind they're) by name in order to count their length, this "deduplicates" types with the same name (like extensions and their original type). Then we just need to find the longest. 

Some notes:
- I'm keeping local vars to gather all types, maybe this would be useful as part of `Results`? One thing to now is that I'm gathering them based on their name, ignoring the rest of the type. But if we want to keep this data around we are losing information: we would have a `struct` or its `extension` but not both. I'm not sure if the current models have some way of keeping these relations while just keeping 1 type in the results. 
- I'm keeping the types in a couple of Dictionary keyed by name. Ideally a Set would be used to avoid duplicates but that doesn't help much since: 1. Type is not hashable; 2. even if we make it hashbable, the types are really different, only their name is the same. 
- For testing I added a new file (so I had to update some numbers) that reflects the exact error reported #1. Tell me if you prefer to test this in another way. 
- I added the test at the end for my convenience but if you prefer it in another position that makes more sense we can move it ^^

I hope this is useful ^^

### CODE REVIEW

File: Sources/SitrepCore/FileVisitor.swift [hunk 1]
```diff
@@ -203,8 +203,11 @@ class FileVisitor: SyntaxVisitor {
         let inheritanceClause = node.inheritanceClause?.inheritedTypeCollection.map {
             "\($0.typeName)".trimmingCharacters(in: .whitespacesAndNewlines)
         } ?? []
+        
+        let name = node.name
+            .trimmingCharacters(in: .whitespaces)
```
Comment (alexito4) [inline Sources/SitrepCore/FileVisitor.swift]: this fixes an issue I've found where some names had an extra space at the end. I think this is because the way SwiftSyntax deals with leading and trailing tokens. 
Without this the `struct Foobar` name was `Foobar` but the `extension Foobar` name was `Foobar `. 
I could do this on the new `collate` code but I think here is more appropriate.

**Comment by twostraws** [comment]
Great work – thank you!
